import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main.jsx";
import NavBar from "../components/NavBar.jsx";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hüseyin Battal | Full Stack Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main/>
    </div>
  );
}
